import React from "react";
import { Metadata } from "next";
import MainLayout from "@/components/layouts/main";

export const metadata: Metadata = {
  title: "Privacy Policy - Sistem Rekam Medis",
  description: "Sistem Rekam Medis",
};

export default function PrivacyPolicy() {
  return (
    <MainLayout>
      <section className="py-10">
        <div className="px-8 space-y-4">
          <h1 className="text-[#3a3a3a] capitalize text-3xl font-bold">
            Privacy Policy
          </h1>
          <div className="flex flex-col gap-8">
            <div className="space-y-4">
              <p className="text-[#4b4f58]">
                This Privacy Policy describes Our policies and procedures on the
                collection, use and disclosure of Your information when You use
                the Service and tells You about Your privacy rights and how the
                law protects You.
              </p>
              <p className="text-[#4b4f58]">
                We use Your Personal data to provide and improve the Service. By
                using the Service, You agree to the collection and use of
                information in accordance with this Privacy Policy. This Privacy
                Policy has been created with the help of the Privacy Policy
                Template.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="text-3xl font-bold text-[#3a3a3a]">
                Interpretation and Definitions
              </h2>
              <h3 className="text-2xl text-[#3a3a3a]">Interpretation</h3>
              <p className="text-[#4b4f58]">
                The words of which the initial letter is capitalized have
                meanings defined under the following conditions. The following
                definitions shall have the same meaning regardless of whether
                they appear in singular or in plural.
              </p>

              <h3 className="text-2xl text-[#3a3a3a]">Definitions</h3>
              <p className="text-[#4b4f58]">
                For the purposes of this Privacy Policy:
              </p>
              <ul className="list-disc pl-4 text-[#4b4f58] space-y-2">
                <li>
                  <strong>Account</strong> means a unique account created for
                  You to access our Service or parts of our Service.
                </li>
                <li>
                  <strong>Affiliate</strong> means an entity that controls, is
                  controlled by or is under common control with a party.
                </li>
                <li>
                  <strong>Application</strong> means the software program
                  provided by the Company downloaded by You on any electronic
                  device, named Medital.
                </li>
                <li>
                  <strong>Company</strong> refers to PT Solusi Dengan Teknologi,
                  Podomoro City, APL Tower, Jl Let Jend S. Parman Kav 28 16th
                  Floor T9, RT.3/RW.5, South Tanjung Duren, Grogol petamburan,
                  West Jakarta City, Jakarta 11470.
                </li>
                <li>
                  <strong>Country</strong> refers to: Indonesia
                </li>
                <li>
                  <strong>Device</strong> means any device that can access the
                  Service such as a computer, a cellphone or a digital tablet.
                </li>
                <li>
                  <strong>Personal Data</strong> is any information that relates
                  to an identified or identifiable individual.
                </li>
                <li>
                  <strong>Service</strong> refers to the Application.
                </li>
                <li>
                  <strong>Service Provider</strong> means any natural or legal
                  person who processes the data on behalf of the Company.
                </li>
                <li>
                  <strong>Usage Data</strong> refers to data collected
                  automatically, either generated by the use of the Service or
                  from the Service infrastructure itself.
                </li>
                <li>
                  <strong>You</strong> means the individual accessing or using
                  the Service, or the company, or other legal entity on behalf
                  of which such individual is accessing or using the Service, as
                  applicable.
                </li>
              </ul>
            </div>

            <div className="space-y-4">
              <h2 className="text-3xl font-bold text-[#3a3a3a]">
                Collecting and Using Your Personal Data
              </h2>
              <h3 className="text-2xl text-[#3a3a3a]">
                Types of Data Collected
              </h3>
              <p className="text-[#4b4f58]">
                While using Our Service, We may ask You to provide Us with
                certain personally identifiable information that can be used to
                contact or identify You. Personally identifiable information may
                include, but is not limited to:
              </p>
              <ul className="list-disc pl-4 text-[#4b4f58] space-y-2">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Usage Data</li>
              </ul>
            </div>

            <div className="space-y-4">
              <h2 className="text-3xl font-bold text-[#3a3a3a]">
                Use of Your Personal Data
              </h2>
              <p className="text-[#4b4f58]">
                The Company may use Personal Data for the following purposes:
              </p>
              <ul className="list-disc pl-4 text-[#4b4f58] space-y-2">
                <li>To provide and maintain our Service</li>
                <li>To manage Your Account</li>
                <li>For the performance of a contract</li>
                <li>To contact You</li>
                <li>
                  To provide You with news, special offers and general
                  information
                </li>
                <li>To manage Your requests</li>
                <li>For business transfers</li>
                <li>For other purposes</li>
              </ul>
            </div>

            <div className="space-y-4">
              <h2 className="text-3xl font-bold text-[#3a3a3a]">
                Security of Your Personal Data
              </h2>
              <p className="text-[#4b4f58]">
                The security of Your Personal Data is important to Us, but
                remember that no method of transmission over the Internet, or
                method of electronic storage is 100% secure. While We strive to
                use commercially acceptable means to protect Your Personal Data,
                We cannot guarantee its absolute security.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="text-3xl font-bold text-[#3a3a3a]">
                Childrens Privacy
              </h2>
              <p className="text-[#4b4f58]">
                Our Service does not address anyone under the age of 13. We do
                not knowingly collect personally identifiable information from
                anyone under the age of 13. If You are a parent or guardian and
                You are aware that Your child has provided Us with Personal
                Data, please contact Us.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="text-3xl font-bold text-[#3a3a3a]">
                Changes to this Privacy Policy
              </h2>
              <p className="text-[#4b4f58]">
                We may update Our Privacy Policy from time to time. We will
                notify You of any changes by posting the new Privacy Policy on
                this page.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="text-3xl font-bold text-[#3a3a3a]">Contact Us</h2>
              <p className="text-[#4b4f58]">
                If you have any questions about this Privacy Policy, You can
                contact us:
              </p>
              <p className="text-[#4b4f58]">By email: jason@medital.id</p>
            </div>
          </div>
        </div>
      </section>
    </MainLayout>
  );
}
